### PR TITLE
Cookiecutter

### LINKED ISSUE #9: Make this a cookiecutter

### PR DESCRIPTION
**Pull request by martinRenou**
Fix #9

### CODE REVIEW

**Comment by martinRenou** [comment]
TODO 
- [x] : Update README
- [x] : Add base README and license
- [x] : Update CI accordingly
- [x] : Use author_name and author_email
- [x] : Use project_short_description

**Comment by martinRenou** [comment]
@jtpio I guess this is ready for review now :)

**Review by jtpio — APPROVED** [review]
Thanks!!

Just tested this locally in a new env with the following and it works well :+1: 

```bash
cookiecutter https://github.com/martinRenou/jupyterlab-app-template --checkout cookiecutter
python -m pip install -e .
jupyter test-app
```

**Comment by jtpio** [comment]
We can also consider this fixes https://github.com/jupyterlab/retrolab/issues/133

**Pull request merged**
